kind: ConfigMap
apiVersion: v1
metadata:
  name: admin-service-app
data:
  application.properties: |-
    server.port: 8001
    misc.message: dupa7
    spring.data.mongodb.uri: mongodb://mongo1-0.mongo1:27017/admin
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: order-service-app
data:
  application.properties: |-
    server.port: 8002
    misc.message: xd2
    spring.data.mongodb.uri: mongodb://mongo3-0.mongo3:27017/order









