apiVersion: v1
kind: Service
metadata:
  name: mongo3
  labels:
    name: mongo3
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo3
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo3
spec:
  serviceName: "mongo3"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo3
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
#          command:
#            - mongod
#            - "--replSet"
#            - rs0
#            - "--smallfiles"
#            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo3-persistent-storage
              mountPath: /data/db
#        - name: mongo-sidecar
#          image: cvallance/mongo-k8s-sidecar
#          env:
#            - name: MONGO_SIDECAR_POD_LABELS
#              value: "role=mongo3,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo3-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "gluster-sc"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
