---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: "/prometheus"
      prometheus.io/port: "9411"
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin"
  spec:
    ports:
    - port: 9411
      protocol: "TCP"
      targetPort: 9411
      nodePort: 30411
    selector:
      project: "zipkin"
      provider: "fabric8"
      group: "io.fabric8.zipkin"
    type: "NodePort"
- apiVersion: "extensions/v1beta1"
  kind: "Deployment"
  metadata:
    annotations:
      fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/git-branch: "release-v0.1.5"
      fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
      fabric8.io/build-id: "3"
      fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
      fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
    labels:
      provider: "fabric8"
      project: "zipkin"
      version: "0.1.5"
      group: "io.fabric8.zipkin"
    name: "zipkin"
  spec:
    replicas: 1
    selector:
      matchLabels:
        provider: "fabric8"
        project: "zipkin"
        group: "io.fabric8.zipkin"
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: "78bd65851c7d9e22652957107fc339a55f80b606"
          fabric8.io/metrics-path: "dashboard/file/kubernetes-pods.json/?var-project=zipkin&var-version=0.1.5"
          fabric8.io/build-id: "3"
          fabric8.io/build-url: "http://jenkins.ux.fabric8.io/job/oss-parent/3"
          fabric8.io/git-branch: "release-v0.1.5"
          fabric8.io/git-url: "http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/78bd65851c7d9e22652957107fc339a55f80b606"
        labels:
          provider: "fabric8"
          project: "zipkin"
          version: "0.1.5"
          group: "io.fabric8.zipkin"
      spec:
        containers:
        - env:
          - name: "STORAGE_PORT_9042_TCP_ADDR"
            value: "zipkin-cassandra:9411"
          - name: "STORAGE_PORT_3306_TCP_ADDR"
            value: "zipkin-mysql:3306"
          - name: "STORAGE_TYPE"
            value: "mysql"
          - name: "TRANSPORT_TYPE"
            value: "http"
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "openzipkin/zipkin:1.13.0"
          name: "zipkin"
          readinessProbe:
            httpGet:
              path: "/api/v1/services"
              port: 9411
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "0"
              memory: "0"
            requests:
              cpu: "0"
              memory: "0"
